### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by lelecoinacioborges** [appticles/wordpress-pwacommerce#4]
Good morning, I get these errors.

Fatal error: Uncaught Error: Call to a member function get_page_permastruct() on null in /customers/9/b/3/xxxxxxxxxxxx/httpd.www/wp-includes/link-template.php:357 Stack trace: #0 /customers/9/b/3/xxxxxxxxxxxxx/httpd.www/wp-includes/link-template.php(320): _get_page_link(Object(WP_Post), false, false) #1 /customers/9/b/3/xxxxxxxxxxxxx/httpd.www/wp-includes/link-template.php(144): get_page_link(Object(WP_Post), false, false) #2 /customers/9/b/3/xxxxxxxxxxxxxxx/httpd.www/wp-content/plugins/woocommerce/includes/wc-page-functions.php(67): get_permalink(Object(WP_Post)) #3 /customers/9/b/3/xxxxxxxxxxx/httpd.www/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1271): wc_get_page_permalink('checkout') #4 /customers/9/b/3/xxxxxxxxxxxxx/httpd.www/wp-content/plugins/pwacommerce/frontend/frontend-init.php(93): wc_get_checkout_url() #5 /customers/9/b/3/xxxxxxxxxxxx/httpd.www/wp-content/plugins/pwacommerce/frontend/frontend-init.php(83): PWAcommerce\Frontend\Frontend_Init->is_checkout_url() #6 in /customers/9/b/3/xxxxxxxx/httpd.www/wp-includes/link-template.php on line 357

**Comment by anghelalexandra** [comment]
@lelecoinacioborges Please follow the bug report template. Can you please also send the following information?

 - PHP Version [e.g. 5.4]
 - WordPress version: [e.g. 4.9.6]
 - WooCommerce plugin version: [e.g. 3.4.0]
 - PWACommerce Plugin Version [e.g. 0.5]
 - Other WooCommerce plugins that you are using
